DROP DATABASE IF EXISTS ECOMMERCE;
CREATE DATABASE ECOMMERCE;
USE ECOMMERCE;

CREATE TABLE CLIENTS(
    ID_CLIENT INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FULLNAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    ADDRESS TEXT NOT NULL,
    CITY TEXT NOT NULL,
    STATE TEXT NOT NULL,
    ZIPCODE TEXT NOT NULL,
    COUNTRY TEXT NOT NULL,
    PHONE TEXT NOT NULL
);

CREATE TABLE ROL(
    ID_ROL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ROL_NAME TEXT NOT NULL
);

CREATE TABLE STORES(
    ID_STORE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT NOT NULL,
    CITY TEXT NOT NULL,
    STATE TEXT NOT NULL,
    ZIPCODE TEXT NOT NULL,
    COUNTRY TEXT NOT NULL,
    PHONE TEXT NOT NULL
);

CREATE TABLE PERSONAL(
    ID_PERSONAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FULLNAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    ID_ROL INT NOT NULL,
    ID_STORE INT NOT NULL,
    FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL),
    FOREIGN KEY (ID_STORE) REFERENCES STORES(ID_STORE)
);

CREATE TABLE PRODUCTS(
    ID_PRODUCT INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PRICE INT NOT NULL,
    STOCK INT NOT NULL,
    ID_STORE INT NOT NULL,
    FOREIGN KEY (ID_STORE) REFERENCES STORES(ID_STORE)
);

CREATE TABLE PROVIDERS(
    ID_PROVIDER INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FULLNAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    /* ADDRESS TEXT NOT NULL,
    CITY TEXT NOT NULL,
    STATE TEXT NOT NULL,
    ZIPCODE TEXT NOT NULL,
    COUNTRY TEXT NOT NULL, */
    PHONE TEXT NOT NULL
);

/* INSERTS OF PROVIDERS */
INSERT INTO PROVIDERS(FULLNAME, EMAIL, PHONE) VALUES('Proveedor 1', 'proveider1@mail.com', '1234567890');
INSERT INTO PROVIDERS(FULLNAME, EMAIL, PHONE) VALUES('Proveedor 2', 'proveider2@mail.com', '1234567890');
INSERT INTO PROVIDERS(FULLNAME, EMAIL, PHONE) VALUES('Proveedor 3', 'proveider3@mail.com', '1234567890');
INSERT INTO PROVIDERS(FULLNAME, EMAIL, PHONE) VALUES('Proveedor 4', 'proveider4@mail.com', '1234567890');

/* INSERTS OF STORE */
INSERT INTO STORES(NAME, ADDRESS, CITY, STATE, ZIPCODE, COUNTRY, PHONE) VALUES('Tienda 1', 'Calle 1', 'Ciudad de Mexico', 'CDMX', '12345', 'Mexico', '1234567890');
INSERT INTO STORES(NAME, ADDRESS, CITY, STATE, ZIPCODE, COUNTRY, PHONE) VALUES('Tienda 2', 'Calle 2', 'Ciudad de Mexico', 'CDMX', '12345', 'Mexico', '1234567890');
INSERT INTO STORES(NAME, ADDRESS, CITY, STATE, ZIPCODE, COUNTRY, PHONE) VALUES('Tienda 3', 'Calle 3', 'Ciudad de Mexico', 'CDMX', '12345', 'Mexico', '1234567890');
INSERT INTO STORES(NAME, ADDRESS, CITY, STATE, ZIPCODE, COUNTRY, PHONE) VALUES('Tienda 4', 'Calle 4', 'Ciudad de Mexico', 'CDMX', '12345', 'Mexico', '1234567890');

/* INSERTS OF CLIENTS */
INSERT INTO CLIENTS(FULLNAME, EMAIL, PASSWORD, ADDRESS, CITY, STATE, ZIPCODE, COUNTRY, PHONE) VALUES('Juan Perez', 'jperez@mail.com', '1234', 'Calle 1', 'Ciudad de Mexico', 'CDMX', '12345', 'Mexico', '1234567890');
INSERT INTO CLIENTS(FULLNAME, EMAIL, PASSWORD, ADDRESS, CITY, STATE, ZIPCODE, COUNTRY, PHONE) VALUES('Maria Lopez', 'mlopez@mail.com', '1234', 'Calle 2', 'Ciudad de Mexico', 'CDMX', '12345', 'Mexico', '1234567890');
INSERT INTO CLIENTS(FULLNAME, EMAIL, PASSWORD, ADDRESS, CITY, STATE, ZIPCODE, COUNTRY, PHONE) VALUES('Pedro Sanchez', 'psanchez@mail.com', '1234', 'Calle 3', 'Ciudad de Mexico', 'CDMX', '12345', 'Mexico', '1234567890');
INSERT INTO CLIENTS(FULLNAME, EMAIL, PASSWORD, ADDRESS, CITY, STATE, ZIPCODE, COUNTRY, PHONE) VALUES('Luisa Garcia', 'lgarcia@mail.com', '1234', 'Calle 4', 'Ciudad de Mexico', 'CDMX', '12345', 'Mexico', '1234567890');

/* INSERTS OF ROL */
INSERT INTO ROL(ROL_NAME) VALUES('ADMIN');
INSERT INTO ROL(ROL_NAME) VALUES('USER');

/* INSERTS OF PERSONAL */
INSERT INTO PERSONAL(FULLNAME, EMAIL, PASSWORD, ID_ROL, ID_STORE) VALUES('Juan Perez', 'jstoreperez@store.com', '1234', 1, 1);
INSERT INTO PERSONAL(FULLNAME, EMAIL, PASSWORD, ID_ROL, ID_STORE) VALUES('Maria Lopez', 'mstorelopez@store.com', '1234', 1, 1);
INSERT INTO PERSONAL(FULLNAME, EMAIL, PASSWORD, ID_ROL, ID_STORE) VALUES('Pedro Sanchez', 'pstoresanchez@store.com', '1234', 1, 1);
INSERT INTO PERSONAL(FULLNAME, EMAIL, PASSWORD, ID_ROL, ID_STORE) VALUES('Luisa Garcia', 'lstoregarcia@store.com', '1234', 1, 1);

/* INSERTS OF PRODUCTS */
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, ID_STORE) VALUES('Producto 1', 'Descripcion 1', 100, 10, 1);
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, ID_STORE) VALUES('Producto 2', 'Descripcion 2', 200, 20, 1);
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, ID_STORE) VALUES('Producto 3', 'Descripcion 3', 300, 30, 1);
INSERT INTO PRODUCTS(NAME, DESCRIPTION, PRICE, STOCK, ID_STORE) VALUES('Producto 4', 'Descripcion 4', 400, 40, 1);

